name: poc-js-front-app-wf

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # GithubHostedRunnerのベースイメージ（他にMac, Windowsが選択可）
    runs-on: ubuntu-latest
    # pipeline-making repoのWFを起動する場合は以下設定を使用する
    # uses: organiztion-name/repository-name/.github/workflows/reusable.yml@main
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runner上の$GITHUB_WORKSPACEの直下に以下レポジトリのsrcがCheckoutされる
      - uses: actions/checkout@v3
        with:
          repository: 'wealsoft/pipeline-making'
          token: ${{ secrets.PAT_PIPELINE_MAKING_REPO }}
          path: './pipeline-making'
          ref: "feature/ozaki_poc"
      - name: Check Pipeline WF
        shell: bash
        run: |
          ls -lha
      - name: 
        shell: bash
        run: |
          ls -lha
