name: poc-js-front-app-wf

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    uses: wealsoft/public-pipeline-making/.github/workflows/js-blog-build-deployment.yml@main
    secrets:
      DOCKERHUB_USER_NAME: ${{ secrets.DOCKERHUB_USER_NAME }}
      DOCKERHUB_USER_PASSWORD: ${{ secrets.DOCKERHUB_USER_PASSWORD }}
      PAT_PIPELINE_MAKING_REPO: ${{ secrets.PAT_PIPELINE_MAKING_REPO }}